import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createDie, createJoker, createEmptyBoard, lockUnlockedDice, placeDie } from '../src/game.js';

class FakeElement {
  constructor(tagName){this.tagName=tagName.toUpperCase();this.children=[];this.dataset={};this.listeners=new Map();this.style={};this.hidden=false;this._className='';this._textContent='';this.disabled=false;this.id='';}
  set className(v){this._className=v} get className(){return this._className}
  get classList(){return { add: c => { this._className += ` ${c}`; } };}
  set textContent(v){this._textContent=String(v);this.children=[]} get textContent(){return this._textContent}
  set innerHTML(v){this._textContent=String(v);this.children=[]} get innerHTML(){return this._textContent}
  appendChild(c){this.children.push(c);return c} prepend(c){this.children.unshift(c);return c}
  addEventListener(t,l){this.listeners.set(t,l)} click(){this.listeners.get('click')?.({ preventDefault(){}, target:this })} submit(){this.listeners.get('submit')?.({ preventDefault(){}, target:this })}
  insertAdjacentHTML(){this.children.push(new FakeElement('span'))}
  showModal(){this.open=true} close(){this.open=false}
  querySelector(){return null}
}
function createFakeDocument(){const ids=['#board','#tray','#roll','#score','#highScore','#message','#jokerWindow','#jokerCountdown','#log','#gameOver','#rankingList','#scoreDialog','#howToDialog','#rankForm','#playerName','#rankSubmit','#gameOverMessage','#rules','#howToPlay','#howToPlayStart','#closeHowTo','#closeRules','#restart','#gameOverRestart','#scoreExamples','#rankingButton','#rankingView','#rankingViewList','#closeRankingView','#modeLabel','#startScreen','#startGame','#rankingNormal','#rankingEasy','#bgmStatus','#bgmToggle','#actionHint','#sfxToggle'];const elements=new Map(ids.map(id=>{const el=new FakeElement(id.slice(1)==='rankForm'?'form':'div');el.id=id.slice(1);return [id,el]}));elements.get('#playerName').value='AAA';elements.get('#gameOver').hidden=true;const doc={selectedMode:'normal',querySelector:s=>{if(s==='input[name=\"gameMode\"]:checked')return{value:doc.selectedMode};const e=elements.get(s);if(!e)throw Error(`Missing ${s}`);return e},querySelectorAll:s=>s==='.cell'?elements.get('#board').children:[],createElement:t=>new FakeElement(t),elements};return doc;}

test('HTML references loadable CSS and JS assets', async()=>{const html=await readFile('index.html','utf8');assert.match(html,/<link rel="stylesheet" href="\.\/src\/styles\.css"/);assert.match(html,/<script type="module" src="\.\/src\/main\.js"><\/script>/);assert.match(html,/<section id="gameOver" class="overlay" hidden aria-hidden="true" style="display:none">/);assert.match(html,/<button id="rankingButton">ランキング<\/button>/);assert.match(html,/<dialog id="rankingView">/);await assert.doesNotReject(readFile('src/styles.css','utf8'));await assert.doesNotReject(readFile('src/main.js','utf8'));});

test('CSS keeps the 4x4 board usable at smartphone widths', async()=>{const css=await readFile('src/styles.css','utf8');assert.match(css,/width:min\(780px,96vw\)/);assert.match(css,/grid-template-columns:repeat\(4,minmax\(58px,1fr\)\)/);assert.match(css,/aspect-ratio:1/);assert.match(css,/\.overlay\[hidden\]\{display:none!important\}/);});

test('SFX controls reference manually uploaded audio files and tolerate missing Audio API', async()=>{const js=await readFile('src/main.js','utf8');const html=await readFile('index.html','utf8');assert.match(html,/<button id="sfxToggle" type="button">SE ON<\/button>/);assert.match(js,/sfxEnabled: 'diceBatchGridSfxEnabled'/);assert.match(js,/erase: 'assets\/audio\/erace\.mp3'/);assert.match(js,/refill: 'assets\/audio\/hojyu\.mp3'/);assert.match(js,/joker: 'assets\/audio\/joker\.mp3'/);assert.match(js,/gameOver: 'assets\/audio\/last\.mp3'/);assert.match(js,/lock: 'assets\/audio\/lock\.mp3'/);assert.match(js,/start: 'assets\/audio\/start\.mp3'/);assert.match(js,/result\?\.catch\?\.\(\(\) => \{\}\)/);});


test('main module renders 4x4 board and 補充 creates four stock dice', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map(),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};const random=Math.random;Math.random=()=>0.5;try{await import(`../src/main.js?smoke=${Date.now()}`);const board=document.elements.get('#board');const tray=document.elements.get('#tray');const roll=document.elements.get('#roll');const message=document.elements.get('#message');assert.equal(board.children.length,16);assert.equal(roll.disabled,true);assert.equal(document.elements.get('#gameOver').hidden,true);document.elements.get('#startGame').click();assert.equal(roll.disabled,false);roll.click();assert.equal(tray.children.length,4);assert.equal(roll.disabled,false);assert.match(message.textContent,/ストック/);const js=await readFile('src/main.js','utf8');assert.match(js,/assets\/dice\/JK\.png/);}finally{Math.random=random;delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});


test('pending joker moves without writing yellow defaults into board data', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map(),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{const mod=await import(`../src/main.js?pending-joker=${Date.now()}`);document.elements.get('#startGame').click();const joker=createJoker();mod.__testing.state.jokerStock=1;mod.__testing.state.pendingJoker={die:joker,row:0,col:0};assert.equal(mod.__testing.state.board[0][0],null);mod.__testing.state.pendingJoker={die:joker,row:0,col:1};assert.equal(mod.__testing.state.board[0][0],null);assert.equal(mod.__testing.state.board[0][1],null);mod.__testing.commitPendingJoker();assert.equal(mod.__testing.state.board[0][1].joker,true);assert.equal(mod.__testing.state.board[0][1].color,'joker');assert.equal(mod.__testing.state.board[0][1].number,0);assert.equal(mod.__testing.state.board[0][0],null);}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});

test('pending joker over locked die restores original board data when moved away', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map(),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{const mod=await import(`../src/main.js?pending-joker-restore=${Date.now()}`);document.elements.get('#startGame').click();const covered=createDie('blue',4);let board=createEmptyBoard();board=placeDie(board,1,1,covered);mod.__testing.state.board=lockUnlockedDice(board).board;const lockedId=mod.__testing.state.board[1][1].id;const joker=createJoker();mod.__testing.state.pendingJoker={die:joker,row:1,col:1};mod.__testing.state.pendingJoker={die:joker,row:2,col:2};assert.equal(mod.__testing.state.board[1][1].id,lockedId);assert.equal(mod.__testing.state.board[1][1].color,'blue');assert.equal(mod.__testing.state.board[2][2],null);mod.__testing.commitPendingJoker();assert.equal(mod.__testing.state.board[1][1].id,lockedId);assert.equal(mod.__testing.state.board[2][2].joker,true);}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});


test('ranking button opens a read-only ranking modal without showing registration form', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map([['diceBatchGridRankingsNormal',JSON.stringify([{name:'AAA',score:500}])]]),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{await import(`../src/main.js?rankview=${Date.now()}`);const modal=document.elements.get('#gameOver');const rankingButton=document.elements.get('#rankingButton');const rankingView=document.elements.get('#rankingView');rankingButton.click();assert.equal(modal.hidden,true);assert.equal(rankingView.open,true);assert.equal(document.elements.get('#rankingViewList').children[0].textContent,'1. AAA 500点');}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});



test('easy mode starts with 280 joker countdown and stores rankings separately from normal', async()=>{const document=createFakeDocument();document.selectedMode='easy';globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map([['diceBatchGridRankingsNormal',JSON.stringify([{name:'NOR',score:700}])],['diceBatchGridRankingsEasy',JSON.stringify([{name:'EZY',score:300}])],['diceBatchGridHighNormal','700'],['diceBatchGridHighEasy','300']]),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{const mod=await import(`../src/main.js?easy=${Date.now()}`);document.elements.get('#startGame').click();assert.equal(mod.__testing.state.mode,'easy');assert.equal(mod.__testing.state.jokerThreshold,280);assert.equal(document.elements.get('#jokerCountdown').textContent,'280点');assert.equal(document.elements.get('#highScore').textContent,'300点');mod.__testing.state.score=450;await mod.__testing.endGame();document.elements.get('#rankForm').submit();assert.equal(JSON.parse(localStorage.getItem('diceBatchGridRankingsEasy'))[0].score,450);assert.equal(JSON.parse(localStorage.getItem('diceBatchGridRankingsNormal'))[0].name,'NOR');}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});

test('ranking view can switch between normal and easy lists', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map([['diceBatchGridRankingsNormal',JSON.stringify([{name:'NOR',score:700}])],['diceBatchGridRankingsEasy',JSON.stringify([{name:'EZY',score:300}])]]),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{await import(`../src/main.js?tabs=${Date.now()}`);document.elements.get('#rankingButton').click();assert.equal(document.elements.get('#rankingViewList').children[0].textContent,'1. NOR 700点');document.elements.get('#rankingEasy').click();assert.equal(document.elements.get('#rankingViewList').children[0].textContent,'1. EZY 300点');document.elements.get('#rankingNormal').click();assert.equal(document.elements.get('#rankingViewList').children[0].textContent,'1. NOR 700点');}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});

test('startup ignores persisted in-progress game-over state and keeps only high score/rankings', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map([['remakeDice.highScore','999'],['diceBatchGridRankingsNormal',JSON.stringify([{name:'AAA',score:500}])],['remakeDice.gameOver','true'],['remakeDice.score','777'],['remakeDice.board','filled']]),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{await import(`../src/main.js?startup=${Date.now()}`);const board=document.elements.get('#board');const tray=document.elements.get('#tray');const roll=document.elements.get('#roll');assert.equal(document.elements.get('#score').textContent,'0点');assert.equal(document.elements.get('#highScore').textContent,'999点');assert.equal(document.elements.get('#gameOver').hidden,true);assert.equal(document.elements.get('#startScreen').hidden,false);document.elements.get('#startGame').click();assert.equal(roll.disabled,false);assert.equal(board.children.length,16);assert.equal(tray.children.length,0);assert.match(document.elements.get('#message').textContent,/補充で4つ/g);assert.equal(document.elements.get('#rankingList').children[0].textContent,'1. AAA 500点');}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});


test('ranking registration is accepted only during game over and resets to a new game once', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map([['remakeDice.highScore','999']]),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};try{const mod=await import(`../src/main.js?ranking=${Date.now()}`);const modal=document.elements.get('#gameOver');const form=document.elements.get('#rankForm');form.submit();assert.equal(localStorage.getItem('diceBatchGridRankingsNormal'),null);mod.__testing.state.score=321;await mod.__testing.endGame();assert.equal(modal.hidden,false);form.submit();assert.equal(modal.hidden,true);assert.equal(document.elements.get('#score').textContent,'0点');assert.equal(document.elements.get('#highScore').textContent,'999点');assert.equal(document.elements.get('#roll').disabled,false);assert.equal(JSON.parse(localStorage.getItem('diceBatchGridRankingsNormal')).length,1);form.submit();assert.equal(JSON.parse(localStorage.getItem('diceBatchGridRankingsNormal')).length,1);assert.match(document.elements.get('#message').textContent,/補充で4つ/g);}finally{delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});

test('game-over restart button resets playable state without ranking registration while preserving storage', async()=>{const document=createFakeDocument();globalThis.document=document;globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.localStorage={store:new Map([['remakeDice.highScore','999'],['diceBatchGridRankingsNormal',JSON.stringify([{name:'OLD',score:100}])]]),getItem(k){return this.store.get(k)||null},setItem(k,v){this.store.set(k,String(v))}};const random=Math.random;Math.random=()=>0.5;try{const mod=await import(`../src/main.js?restart=${Date.now()}`);const tray=document.elements.get('#tray');const roll=document.elements.get('#roll');const modal=document.elements.get('#gameOver');const restart=document.elements.get('#gameOverRestart');roll.click();assert.equal(tray.children.length,4);mod.__testing.state.score=222;await mod.__testing.endGame();restart.click();assert.equal(modal.hidden,true);assert.equal(tray.children.length,0);assert.equal(document.elements.get('#score').textContent,'0点');assert.equal(document.elements.get('#highScore').textContent,'999点');assert.equal(document.elements.get('#jokerCountdown').textContent,'400点');assert.equal(roll.disabled,false);assert.equal(JSON.parse(localStorage.getItem('diceBatchGridRankingsNormal')).length,1);assert.equal(JSON.parse(localStorage.getItem('diceBatchGridRankingsNormal'))[0].name,'OLD');assert.equal(localStorage.getItem('remakeDice.highScore'),'999');assert.match(document.elements.get('#message').textContent,/補充で4つ/g);}finally{Math.random=random;delete globalThis.document;delete globalThis.window;delete globalThis.localStorage;}});
